export function generateMockProposals(scenarioId: string) {
  const proposalTemplates = {
    "potato-chips": [
      {
        materialName: "バイオPP単層フィルム",
        composition: "Bio-PP/EVOH coating",
        scores: {
          physical: 85,
          environmental: 92,
          cost: 70,
          safety: 95,
          supply: 75,
        },
        totalScore: 83,
        reasoning: "植物由来のポリプロピレンにEVOHコーティングを施すことで、優れたバリア性を維持しながらモノマテリアル化を実現。リサイクル性が大幅に向上し、CO2排出量を40%削減可能。",
        features: ["モノマテリアル", "バイオマス由来", "リサイクル可能", "高バリア性"],
        dataSources: ["Convexデータベース", "最新Web情報", "AI分析"],
      },
      {
        materialName: "紙/バイオPEラミネート",
        composition: "Paper/Bio-PE",
        scores: {
          physical: 75,
          environmental: 88,
          cost: 85,
          safety: 90,
          supply: 80,
        },
        totalScore: 84,
        reasoning: "FSC認証紙にバイオマス由来PEをラミネート。紙の割合を70%以上にすることで紙リサイクルルートで処理可能。消費者の環境意識にも訴求しやすい。",
        features: ["紙ベース", "FSC認証", "バイオPE使用", "既存設備対応"],
        dataSources: ["Convexデータベース", "業界トレンド分析"],
      },
      {
        materialName: "高バリアPETモノマテリアル",
        composition: "PET/SiOx coating",
        scores: {
          physical: 90,
          environmental: 75,
          cost: 75,
          safety: 92,
          supply: 85,
        },
        totalScore: 83,
        reasoning: "PETに酸化ケイ素蒸着処理を施した単一素材構成。既存のPETリサイクルインフラを活用可能で、透明性も維持できるため商品の視認性も確保。",
        features: ["単一素材", "透明性維持", "高バリア", "既存インフラ活用"],
        dataSources: ["技術データベース", "特許情報分析"],
      },
    ],
    "frozen-food": [
      {
        materialName: "バイオPE単層フィルム",
        composition: "Bio-PE/EVOH/Bio-PE",
        scores: {
          physical: 88,
          environmental: 85,
          cost: 72,
          safety: 94,
          supply: 78,
        },
        totalScore: 83,
        reasoning: "サトウキビ由来のPEを使用し、中間層にEVOHを配置。-18℃での柔軟性を維持しながら、電子レンジ対応も可能。カーボンニュートラルに貢献。",
        features: ["バイオマス", "冷凍対応", "電子レンジ可", "低温柔軟性"],
        dataSources: ["Convexデータベース", "最新研究論文"],
      },
      {
        materialName: "リサイクルPP複合材",
        composition: "r-PP/EVOH/r-PP",
        scores: {
          physical: 82,
          environmental: 80,
          cost: 88,
          safety: 90,
          supply: 82,
        },
        totalScore: 84,
        reasoning: "ケミカルリサイクルPPを使用した3層構造。バージン材と同等の物性を持ち、コスト面でも優位性あり。循環型経済に貢献。",
        features: ["リサイクル材", "コスト優位", "循環型", "実績豊富"],
        dataSources: ["市場データ", "サプライヤー情報"],
      },
      {
        materialName: "植物由来PA/PE",
        composition: "Bio-PA/Bio-PE",
        scores: {
          physical: 85,
          environmental: 82,
          cost: 68,
          safety: 91,
          supply: 73,
        },
        totalScore: 80,
        reasoning: "ヒマシ油由来のポリアミドとバイオPEの組み合わせ。優れた耐ピンホール性と落下強度を実現。将来的な量産化でコスト削減見込み。",
        features: ["植物由来", "高強度", "耐ピンホール", "将来性"],
        dataSources: ["技術トレンド", "開発者インタビュー"],
      },
    ],
    "coffee-beans": [
      {
        materialName: "バリアコート紙",
        composition: "Paper/Bio-barrier coating",
        scores: {
          physical: 78,
          environmental: 95,
          cost: 82,
          safety: 93,
          supply: 77,
        },
        totalScore: 85,
        reasoning: "特殊バリアコーティングを施した紙素材。コンポスト可能で、6ヶ月の賞味期限を確保。脱気バルブも紙製で統一可能。",
        features: ["コンポスト可能", "紙製", "バリア性", "環境配慮"],
        dataSources: ["Convexデータベース", "環境認証データ"],
      },
      {
        materialName: "バイオPBS/PBAT",
        composition: "Bio-PBS/PBAT blend",
        scores: {
          physical: 82,
          environmental: 90,
          cost: 75,
          safety: 91,
          supply: 72,
        },
        totalScore: 82,
        reasoning: "生分解性プラスチックのブレンド材。土壌中で完全分解し、優れたガスバリア性を実現。香り保持性能も従来材と同等。",
        features: ["生分解性", "土壌分解", "香り保持", "バリア性"],
        dataSources: ["研究データ", "フィールドテスト結果"],
      },
      {
        materialName: "リサイクルPET/バイオコート",
        composition: "r-PET/Bio-barrier",
        scores: {
          physical: 86,
          environmental: 78,
          cost: 85,
          safety: 92,
          supply: 88,
        },
        totalScore: 86,
        reasoning: "メカニカルリサイクルPETに植物由来バリアコーティング。既存のリサイクルシステムを活用可能で、供給安定性も高い。",
        features: ["リサイクル材", "既存システム", "安定供給", "コスト効率"],
        dataSources: ["市場分析", "LCA評価"],
      },
    ],
    "beverage-bottle": [
      {
        materialName: "100% バイオPET",
        composition: "Bio-PET",
        scores: {
          physical: 92,
          environmental: 88,
          cost: 65,
          safety: 95,
          supply: 70,
        },
        totalScore: 82,
        reasoning: "植物由来原料100%のPET。従来PETと同等の物性を持ち、既存の製造・リサイクル設備をそのまま使用可能。カーボンフットプリント50%削減。",
        features: ["100%バイオ", "既存設備対応", "CO2削減", "透明性維持"],
        dataSources: ["Convexデータベース", "LCA分析"],
      },
      {
        materialName: "ケミカルリサイクルPET",
        composition: "cr-PET",
        scores: {
          physical: 90,
          environmental: 82,
          cost: 78,
          safety: 94,
          supply: 85,
        },
        totalScore: 86,
        reasoning: "化学的再生により品質劣化なくリサイクル。食品接触グレードを維持し、無限リサイクルが可能。供給体制も整備されつつある。",
        features: ["無限リサイクル", "品質維持", "食品グレード", "循環型"],
        dataSources: ["技術評価", "市場動向"],
      },
      {
        materialName: "PEF（ポリエチレンフラノエート）",
        composition: "PEF",
        scores: {
          physical: 95,
          environmental: 85,
          cost: 60,
          safety: 93,
          supply: 65,
        },
        totalScore: 80,
        reasoning: "次世代バイオプラスチック。PETより10倍優れたガスバリア性を持ち、100%植物由来。量産化により将来的なコスト低減が期待。",
        features: ["次世代素材", "超高バリア", "100%植物", "軽量化"],
        dataSources: ["最新研究", "開発ロードマップ"],
      },
    ],
  };

  return proposalTemplates[scenarioId] || proposalTemplates["potato-chips"];
}